apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
{{- toYaml .Values.selectorLabels | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
